[window]
opacity = 0.95
padding.x = 0
padding.y = 0
decorations = "None"

[font]
normal ={ family =  "JetBrainsMono Nerd Font Mono", style="Light" }
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"
# offset = {x=0, y=4}
# glyph_offset = {x=0 , y=4}
size = 13.0
