import = [
  "~/.config/alacritty/cyberdream.toml"
]

[window]
opacity = 0.8
padding.x = 0
padding.y = 0
decorations = "Buttonless"
option_as_alt = "both"

[font]
normal ={ family =  "JetBrainsMono Nerd Font Mono", style="Regular" }
bold.family = "JetBrainsMono Nerd Font Mono"
italic.family = "JetBrainsMono Nerd Font Mono"
bold_italic.family = "JetBrainsMono Nerd Font Mono"
offset = {x=0, y=8}
glyph_offset = {x=0 , y=4}
size = 14.0
